version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    volumes:
      - ./backend:/app 
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/management
  frontend:
    build: ./user-task-app
    ports:
      - "4200:4200"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data:


